name: skript-itemsadder
authors: [Asleepp]
description: A Skript Addon that adds useful syntax to be used in conjunction with ItemsAdder
api-version: 1.13
version: ${version}
main: me.asleepp.SkriptItemsAdder.SkriptItemsAdder
depend: [Skript, ItemsAdder]


commands:
  skriptitemsadder:
    description: Reload the plugin's config or see information